### ISSUE TITLE
Performance regression since coursier 2.1.17

### ISSUE THREAD

**Issue by xerial** [coursier/coursier#3190] opened 2024-12-13 23:22 UTC
sbt 1.10.6, which uses coursier 2.1.19 https://github.com/sbt/sbt/pull/7920, has performance regression in the update task, as reported in https://github.com/sbt/sbt/issues/7945

In sbt 1.10.5 with coursier 2.1.14 (1 second):
```bash
$ gh repo clone wvlet/wvlet
$ cd wvlet
# Edit project/build.properties to use sbt 1.10.5
$ ./sbt 
sbt:wvlet> runner/update
[success] Total time: 1 s, completed Dec 13, 2024, 11:08:53 AM
```
In sbt 1.10.6 with coursier 2.1.19 (59 seconds):
```
# Edit project/build.properties to use sbt 1.10.6
sbt:wvlet> runner/update
[success] Total time: 59 s, completed Dec 13, 2024, 11:12:14 AM
-- The second run still takes longer time than sbt 1.10.5
sbt:wvlet> runner/update
[success] Total time: 6 s, completed Dec 13, 2024, 11:13:36 AM
```

## Problem

Resolving some of the Java dependencies (Trino -> Apache Hadoop related dependencies?) in this build.sbt takes quite a long time. It was 1 second in sbt 1.10.5, but sbt 1.10.6 requires almost 1 minute:
https://github.com/wvlet/wvlet/blob/2987497fbc906149bb77c2a77d600b7f6270e2e9/build.sbt#L338-L355

Even after the first update run, there is still significant overhead. 

This slowness can be reproduced with cs resolve command:
```sh
$ cs version
2.1.21
$ time cs resolve -q io.trino:trino-hive:467
... 
cs resolve -q io.trino:trino-hive:467  24.91s user 0.56s system 100% cpu 25.341 total
```

**Comment by SethTisue** [comment] 2024-12-13 23:36
is the problem reproducible outside of sbt with command-line coursier?

**Comment by xerial** [comment] 2024-12-14 00:00
@SethTisue Good question! Yes. It was reproducible with cs resolve command:

```sh
$ > cs version
2.1.21
$ time cs resolve -q io.trino:trino-hive:467
... 
cs resolve -q io.trino:trino-hive:467  24.91s user 0.56s system 100% cpu 25.341 total
```

```sh
$ curl -fLo coursier-2.1.14 https://github.com/coursier/launchers/raw/b3ce633519807c9208bcacbd8f0a7b298014e92d/coursier && chmod +x coursier-2.1.1
$ ./coursier-2.1.14 version                                                                                                                    [15:56:49 Dec 13 2024]
2.1.14
$ time ./coursier-2.1.14 resolve -q io.trino:trino-hive:467
...
./coursier-2.1.14 resolve -q io.trino:trino-hive:467  5.98s user 0.57s system 240% cpu 2.724 total
```

**Comment by eed3si9n** [comment] 2024-12-14 23:40
For future record, this is likely due to https://github.com/coursier/coursier/pull/3097 (Add better support for dependency management (aka BOM)) that got added in Coursier 2.1.17. Curious if the problem is caused by more IO, algorithmic issues, like we have quadratic logic, or some combination of both.

**Comment by xerial** [comment] 2024-12-16 21:03
I've confirmed this regression happened since coursier 2.1.17: 
```
./coursier-2.1.17 resolve -q io.trino:trino-hive:467  15.43s user 0.69s system 152% cpu 10.560 total
./coursier-2.1.16 resolve -q io.trino:trino-hive:467  5.31s user 0.57s system 257% cpu 2.281 total
```

**Comment by protocol7** [comment] 2024-12-17 14:32
We're also seeing this. We're using coursier through Bazel's rules_jvm_external and have patched the coursier version to get access to the BOM support, but resolving takes ages in 2.1.17. We have some 1200 artifacts in total, and resolution normally takes <30 s, with 2.1.17 it does not finish after 20 minutes (have not tried running it for longer). This is without using any `--bom` argument.

**Comment by eed3si9n** [comment] 2024-12-17 14:58
It's been a while since I used flamegraph but here's a way to set it up if anyone wants to give it a shot - https://github.com/sbt/sbt/blob/1.10.x/PROFILING.md

**Comment by alexarchambault** [comment] 2024-12-18 20:11
The perf regression seems to originate recent BOM-related changes, indeed. These were [kind of expected](https://github.com/coursier/coursier/pull/3097#issuecomment-2445031593). I was actually surprised not to have run into significant slow-downs in the coursier test suite.

The new BOM handling stuff can be disabled in newer versions if needed, see [here](https://github.com/coursier/coursier/pull/3097#issuecomment-2462556194) (not sure how to do it in sbt though).

**Comment by alexarchambault** [comment] 2024-12-18 20:25
On a side note, one can notice that resolving `io.trino:trino-hive:467` succeeds with `2.1.17+`, while it was failing before that (on the command-line, or silently ignoring conflicts in sbt), as it couldn't reconcile some grpc-related versions.

**Comment by eed3si9n** [comment] 2024-12-22 22:07
Here's a PR to expose the option to sbt for opt-in/out - https://github.com/coursier/sbt-coursier/pull/545

**Closed** 2024-12-26 20:05 UTC

**Comment by alexarchambault** [comment] 2024-12-27 10:12
FYI coursier `2.1.23`, with optimizations, is out

**Comment by alexarchambault** [comment] 2024-12-27 10:12
> We're also seeing this. We're using coursier through Bazel's rules_jvm_external and have patched the coursier version to get access to the BOM support, but resolving takes longer than expected in 2.1.17. We have some 1200 artifacts in total, and resolution normally takes <30 s, with 2.1.17 it does not finish after 20 minutes (have not tried running it for longer). This is without using any `--bom` argument.

@protocol7 Is it possible for you to share the dependency list (or part of it) that you're fetching? That could be helpful to further optimize things.

I have other optimizations in mind, but I guess these can wait a bit.

**Comment by protocol7** [comment] 2024-12-27 11:37
> @protocol7 Is it possible for you to share the dependency list (or part of it) that you're fetching? That could be helpful to further optimize things.

It contains a mix of internal and external dependencies, but let me see if I can clean up a version that can be shared. Will first test with 2.1.23 and report back. Thanks for tackling this so quickly!

**Comment by protocol7** [comment] 2024-12-27 12:03
Did a quick comparison of 2.1.8 (which is the version that comes with Bazel's rules_jvm_external and thus what we currently use) and 2.1.23. With our full dependency set (1224 dependencies)`REPIN=1 bazel run @maven//:pin` takes 25 s with 2.1.8 and ~48 s with 2.1.23. This is with changing the version of a single dependency and with everything otherwise cached. We are not using `--bom` here.

While 2x slower, this is a huge improvement over 2.1.21 which would time out after 1200 s (didn't have enough patience to run it for longer). Further improvements would of course be welcome, but I think this unblocks the upgrade for us at least.

Here's a gist of what rules_jvm_external invokes coursier with, with our dependency set excluding internal dependencies: https://gist.github.com/protocol7/33c0fe629697dca3eed1167deb78ddd5.
