### ISSUE TITLE
Reducing coursier dependencies

### ISSUE THREAD

**Issue by mdedetrich** [coursier/coursier#175] opened 2016-02-25 04:46 UTC
This issue is going to be highly controversial and may not even be considered due to the conflict of some of the design aims of coursier, essentially the issue is about removing dependencies which are either very large (scalaz) or create circular dependencies with libraries that may want to use coursier (ammonite-terminal, @lihaoyi is considering making ammonite use coursier)

If coursier's aims are to be included in tools like SBT/ammonite (and others) by default, the dependencies need to be made as small as possible. Scalaz unfortunately, due to its monolithic design, weighs in at around 10mb.

There are obviously replacements for Scalaz (the other extreme would be just using the stdlib, which has `Future`), but this obviously means that the core of coursier isn't going to be completely "pure" (from a pure functional programming POV), i.e.

> The cache module handles caching of the metadata and artifacts themselves, and is less so pure than the core module, in the sense that it happily does IO as a side-effect (always wrapped in Task, and naturally favoring immutability for all that's kept in memory).

Other solutions can include using cats instead of Scalaz (cats core is currently much smaller, weighing at 2.7mb currently). Either that, or using an internal solution to replace the areas that Scalaz is being used for (i.e. Task)

Also using Future instead of Task can possibly provide performance improvements since a lot of high performance HTTP libraries (dispatch with netty or akka-http) are backed by Future's

**Comment by ngbinh** [comment] 2016-02-25 06:54
How's about using shaded jars to avoid any conflict instead? https://github.com/sbt/sbt-assembly#shading

**Comment by mdedetrich** [comment] 2016-02-25 07:19
If its possible to use proguard/shading successfully than it would definitely help. Shading will help with the ammonite issue, not sure how effective proguard is at reducing binary size for things like Scalaz (can anyone here comment on that?)

**Comment by alexarchambault** [comment] 2016-02-25 09:16
@mdedetrich It's not controversial at all! I even tried to similar things in circe recently (https://github.com/travisbrown/circe/pull/28), without succeeding in convincing its author.

Dropping the ammonite-terminal dependency is no brainer. I used at first because I didn't know to what extent I would have to use its features, nor if what I was using was stable or not (so the dependency gives free updates), but it turns out coursier doesn't use much from it.

From scalaz, coursier mainly uses `Monad` in core and `Task` in cache, and `EitherT` in the both of them.

I see two ways of dropping the scalaz (or cats) dependency in the future:
- a porcelain module should be added soon, without scalaz explicitly appearing in its API. This module could shade/proguard the main dependencies of coursier, to get a not-too-heavyweight library. To get an idea of its size, the current cli module is published proguarded (https://oss.sonatype.org/content/repositories/releases/com/github/alexarchambault/coursier-cli_2.11/1.0.0-M8/coursier-cli_2.11-1.0.0-M8-standalone.jar), and weights about 1.6 MB. Not having scala-library in it could be 200-300 kB less.
- stop depending on either scalaz or cats, and implement our own basic functional stuff, like fs2 does. This may actually be the less heavyweight choice, if ever the former one turns out impractical.

There are a few higher priority things I'd like to do before that, for a 1.0 final (some stability fixes, and integration tests). But that should be the next thing to do IMO.

**Comment by nafg** [comment] 2016-02-25 11:29
Is this a duplicate of #25?

**Comment by alexarchambault** [comment] 2016-02-25 12:48
@nafg More or less... This one is more general. https://github.com/alexarchambault/coursier/issues/25 is only about substituting cats to scalaz.

**Comment by fommil** [comment] 2016-03-25 22:48
I'd also really like to see a slimmer coursier as it means it can be used as a generic deployment tool without having to bootstrap itself, and we could potentially distribute an assembly/proguarded jar with its full source code with the various ensime clients.

**Comment by alexarchambault** [comment] 2016-03-25 23:15
@fommil Bootstrapping should be better now (since 1.0.0-M10, maybe M9). It only downloads a single proguarded ~1.5 MB JAR, instead of ~25 MB of JARs previously.

**Comment by fommil** [comment] 2016-03-25 23:17
definitely an improvement, but as a longer term goal getting the size of that 1.5MB jar down even further would be good :smile:

**Comment by djspiewak** [comment] 2016-08-31 16:44
Just to weigh in on this…  We've been making various attempts to use Coursier at Verizon, getting closer each time, but our latest thrust was foiled by none other than dependency hell.  Specifically, we have a plugin dependency that uses argonaut under the surface, which in turn depends on Scalaz 7.1.  Since Coursier depends on Scalaz 7.2, this results in a conflict (which is evicted in favor of 7.2) that ultimately generates a bytecode validation error in the dependent plugin.

Dependencies suck a lot.  I wish I had a good solution, but certainly the situation right now is not ideal.

**Comment by alexarchambault** [comment] 2016-08-31 18:28
@djspiewak Would having the plugins switch to argonaut 6.1a be an option? It basically has the same API as 6.1, but depends on scalaz 7.2.

**Comment by djspiewak** [comment] 2016-08-31 18:29
@alexarchambault That's what we're working on.  It is an option in our case, but might not be in others.

**Comment by leonardehrenfried** [comment] 2018-02-07 15:02
@alexarchambault has been publicly on board with removing scalaz as a dependency: sbt/librarymanagement#190 (comment)

This is a prerequisite for sbt starting to ship with coursier support itself (not a plugin).

From a cursory look at the code it seems that the main usages are Task, \/, EitherT. It's not an impossible task to replace these.

The question is: What should it be replaced with?

From my point of view there are a few options:

1. Copy the parts of Scalaz that are actually used.
1. Rewrite the parts that are actually used with types that enhance stdlib functionality.
1. Use another functional library, for example cats.

In my view 3. does not improve the dependency situation much.

So 1. and 2. are more promising.

I'm not sure however, how easy it is to take a part of scalaz and copy it without having to bring in a huge chunk of the rest of the library.

On the other hand, writing a replacement might also be a never-ending project, as the devil is probably in the details.

One approach could be to go type by type, ie. set the goal to remove a single type first and learn from the experiences of doing that. For example, we could introduce a coursier.concurrent.Task and see how far we get.

WDYT?

**Comment by nafg** [comment] 2018-02-07 16:45
How many lines of code is Task?

**Comment by alexarchambault** [comment] 2018-02-07 17:14
@leonardehrenfried I'll handle that issue. For the core module, I'll likely use SHIMs for `Monad`, `EitherT`, maybe `Nondeterminism`, with the bare minimum methods (I tried some time ago, it seemed to work fine…).

Then maybe a type class in cache abstracting over `Task`, and, if possible, a `Future`-backed implementation of it. And cats-effect and scalaz-concurrent modules with cats / scalaz implementations for it.

**Comment by alexarchambault** [comment] 2018-10-29 09:36
coursier `1.1.x` (only released via milestones) doesn't depend on scalaz anymore. The coursier and coursier-cache modules should basically only depend on scala-library and scala-xml.

**Closed by alexarchambault** 2018-10-29 09:36 UTC
