### ISSUE TITLE
Allow bootstraps to read .jvmopts

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1755] opened 2020-06-02 15:27 UTC
Currently, bootstraps pass the content of `$JAVA_OPTS` and of options starting with `-J` (stripping the `-J`) as java options. Adding the possibility to read options from files too could be convenient. This could be used by the [sbt launcher](https://github.com/coursier/apps/blob/0bf140f78d683871605d549bed92acbf39da79af/apps/resources/sbt.json) installed by `cs setup` / `cs install`.

Adding this feature to bootstrap should be optional (and disabled by default), as these files are usually not around for any JVM application, but only for some specific apps.

**Comment by julienrf** [comment] 2022-02-08 08:17
Should we close this issue?

~~~ text
$ cat .jvmopts 
dummy
$ sbt
Error: Could not find or load main class dummy
Caused by: java.lang.ClassNotFoundException: dummy
copying runtime jar...
mkdir: cannot create directory ‘’: No such file or directory
Error: Could not find or load main class dummy
Caused by: java.lang.ClassNotFoundException: dummy
Error: Could not find or load main class dummy
Caused by: java.lang.ClassNotFoundException: dummy
~~~

**Closed** 2022-02-08 09:21 UTC
