### ISSUE TITLE
Hangs when resolving against Artifactory with auth

### ISSUE THREAD

**Issue by avdv** [coursier/coursier#1179] opened 2019-05-21 08:43 UTC
Hi.

Coursier does not cope with dynamic revisions which do not end with a numeric part before the `+`, e.g. like "1.2.3-rc-+".

Up until version 1.1.0-M13-4, this resulted in a resolution error, but starting with 1.1.0-M14, it just hangs.

~Here's a minimal project to reproduce: https://github.com/avdv/coursier-hang~

edit: The reproducer is not really significant, since it only hangs when I have a resolver configured which requires credentials.

**Comment by avdv** [comment] 2019-05-21 08:44
Note, originally brought up here: sbt/sbt#4700 when I was trying SBT 1.3.0-RC1.

**Comment by countfloyd** [comment] 2019-05-21 18:04
Was going to make an issue for this, but I get the same problem with our private Artifactory repo. As mentioned, 1.1.0-M13-4 works ok but M14 hangs.

We are using open-source Artifactory 6.10.0 with credentials required. We are specifying credentials in a credentials.properties file and importing them with:

```
credentials += Credentials(file("credentials.properties"))
```

**Comment by alexarchambault** [comment] 2019-06-17 15:02
Some related things were fixed in coursier `1.1.0-M14-3` (used since sbt-coursier `1.1.0-M14-2`). This should have addressed some possible infinite redirection loops, the redirection code could have gone into.

Did you try with a more recent plugin?

**Comment by countfloyd** [comment] 2019-06-17 15:09
Yes, works for me now, with sbt-coursier-1.1.0-M14-4. Thank you!

**Comment by alexarchambault** [comment] 2019-06-17 15:37
Ok, closing this issue then.

**Comment by countfloyd** [comment] 2019-06-17 16:20
So sorry, you might want to reopen. It was working for a bit but I came across a case where it hung again. Same problem with a private artifactory repo.

**Comment by alexarchambault** [comment] 2019-06-17 16:35
@countfloyd A repro would be welcome then… Like something where we launch an artifactory like
```bash
$ docker run -it --rm -p 8081:8081 docker.bintray.io/jfrog/artifactory-oss:6.10.3
```
then steps to set it up, with artifacts that make resolution hang.

**Comment by avdv** [comment] 2019-06-18 16:01
Hi.

The problem shows when you try to resolve a non-existent artifact. And coursier does not just hang, it actually does something -- it loops between 401 and 404:
```
/project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml.sha1 401
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml 401
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml.sha1 401
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml.sha1 404
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml.sha1 401
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml 401
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml.sha1 404
GET /project-ivy-virtual/com.sample/common-lib_2.12/19.23.0-does-not-exist/ivys/ivy.xml 404
...
```
It does that happily forever...

I used SBT 1.3.0-RC2 and also tried to use the latest coursier RC:
```plugins.sbt
// project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M14-4")

libraryDependencies += "io.get-coursier" %% "coursier" % "v2.0.0-RC2-2"
```

**Comment by alexarchambault** [comment] 2019-06-18 16:23
Thanks for the details @avdv. I'm aware the issue is around the code handling redirection. An actual repro that *I* (or anyone) could run on its own machine would help speeding up fixing this issue.

**Comment by countfloyd** [comment] 2019-06-18 16:47
My issue happens when the artifact exists. Still finding time to work on a test case.

**Comment by countfloyd** [comment] 2019-06-18 18:29
Just another data point: I can't reproduce the problem with CLI 2.0.0-RC2-2. Only happens with the sbt plugin 1.1.0-M14-4

**Comment by countfloyd** [comment] 2019-06-18 18:57
@alexarchambault could I email you with a test case against our repo?

**Comment by alexarchambault** [comment] 2019-06-18 23:27
@countfloyd Sure. See my mail in the git commits.

**Comment by avdv** [comment] 2019-06-19 07:04
I also have updated the avdv/coursier-hang project with a nginx config + docker-compose file. Hope this helps finding the issue...

**Closed** 2019-06-19 11:20 UTC
