### ISSUE TITLE
Still not able to setup on M1 mac

### ISSUE THREAD

**Issue by mtomko** [coursier/coursier#2516] opened 2022-08-22 14:55 UTC
```shell
$ uname -a
Darwin mbp14.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    17.0.4 (arm64) "GraalVM Community" - "GraalVM CE 22.2.0" /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home
    11.0.16 (arm64) "GraalVM Community" - "GraalVM CE 22.2.0" /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.2.0/Contents/Home
/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home
$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06, mixed mode)
$ ./cs-aarch64-apple-darwin version
2.1.0-M6-53-gb4f448130
$ ./cs-aarch64-apple-darwin setup
Checking if a JVM is installed
Found a JVM installed under /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.2.0/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
JVM graalvm:19.3 not found in index: JVM graalvm not found
$
```

I'm happy to try and help solve the problem, but I'm not sure where this message is coming from. It seems like it's from within coursier itself? Could it be related to https://github.com/coursier/coursier/issues/2487?

**Comment by mtomko** [comment] 2022-08-22 14:57
Deleting `$HOME/Library/Caches/Coursier` might have helped.

**Comment by SethTisue** [comment] 2022-09-19 00:27
I'm very interested in learning how to resolve this

**Comment by christianharrington** [comment] 2022-09-27 08:32
I have an idea as to what's causing this, but I don't have an Apple Silicon machine to test on at the moment.

From testing on a coworker's machine, it's installing bloop specifically during setup that causes the crash. If you specify the apps explicitly (with `--apps`) and omit bloop or use bloop-jvm instead, everything works.

The "app" [definition](https://github.com/coursier/apps/blob/master/apps/resources/bloop.json) for bloop specifies that it has the `graalvm-native-image` launcher type.

It [looks like](https://github.com/coursier/coursier/blob/master/modules/install/src/main/scala/coursier/install/InstallDir.scala#203) Coursier uses GraalVM in this case, which I think defaults to the version 19.3 which is specified [here](https://github.com/coursier/coursier/blob/15763afdaf6e87a394d66c3bcdd06149afa9a91c/modules/cli/src/main/scala/coursier/cli/install/SharedInstallOptions.scala#L48). 

Since this version isn't published for ARM, everything fails.

It seems there's a [hidden parameter](https://github.com/coursier/coursier/blob/15763afdaf6e87a394d66c3bcdd06149afa9a91c/modules/cli/src/main/scala/coursier/cli/install/SharedInstallOptions.scala#L19) `--graalvm-default-version` that can be used to override the GraalVM version, but this doesn't fix the issue either, since it looks like Macs need to use `grallvm-java11` or `graalvm-java17`, and the parameter only sets the version. For example `--graalvm-default-version 22.2` causes the setup to fail since there's no `graalvm:22.2`.

I haven't been able to figure out where the string `graalvm:22.2` is built. 

I think if we could change the default GraalVM to `graalvm-java11:22.0` it might work.

**Comment by christianharrington** [comment] 2022-09-27 09:18
Another, potentially safer workaround might be to change the app definition for bloop to not use native-image and/or release Apple Silicon builds for bloop.

**Comment by damlys** [comment] 2022-09-27 09:38
I check [DefaultAppList](https://github.com/coursier/coursier/blob/v2.1.0-M7/modules/cli/src/main/scala/coursier/cli/setup/DefaultAppList.scala) and it seems `scala-cli` app is responsible for this issue 😬

```
$ cs setup --yes --apps ammonite,cs,coursier,scala,scalac,sbt,sbtn,scalafmt
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-11-openjdk-arm64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
  Found sbt
No main class found

$ cs setup --yes --apps scala-cli
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-11-openjdk-arm64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
JVM graalvm:19.3 not found in index: JVM graalvm not found

```

**Comment by mtomko** [comment] 2022-09-30 03:42
I was able to install a bunch of things this way, thanks @christianharrington (and greetings, it's been a while!). I've installed the following apps:
```
amm
bloop-jvm
coursier
cs
sbt
scala
scalac
scalafmt
```

It's probably a separate issue but running `cs` doesn't work for me however:

```shell
cs
/Users/mark/Library/Application Support/Coursier/bin/cs: line 2: /Users/mark/Library/Application Support/Coursier/bin/.cs.aux: cannot execute binary file
/Users/mark/Library/Application Support/Coursier/bin/cs: line 2: /Users/mark/Library/Application Support/Coursier/bin/.cs.aux: Undefined error: 0
```

I think the `No main class found` message is coming from installing `sbtn`:

```shell
$ ./cs-aarch64-apple-darwin setup --yes --apps sbtn
Checking if a JVM is installed
Found a JVM installed under /Users/mark/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz/graalvm-ce-java11-22.2.0/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
No main class found
```

**Comment by damlys** [comment] 2022-09-30 06:14
I can confirm that `sbtn` throws `No main class found` error. This is how my Dockerfile looks like 🙈

```Dockerfile
RUN cs install \
  sbt \
  scala \
  scalac \
  scalafmt \
  && cs install sbtn || true
```

**Comment by alexarchambault** [comment] 2022-11-10 10:13
cc @rochala 

On M1, we may want to check for ARM binaries, and fall back on x86-64 ones.

**Comment by mkurz** [comment] 2022-11-10 10:38
Please also see https://github.com/coursier/coursier/issues/2537#issuecomment-1273791648

**Comment by julienrf** [comment] 2022-12-09 08:17
I am closing this issue as a duplicate of #2537.

**Closed by julienrf** 2022-12-09 08:17 UTC
Labels: high priority
