### ISSUE TITLE
Checksum error from private Nexus

### ISSUE THREAD

**Issue by djspiewak** [coursier/coursier#319] opened 2016-08-09 22:55 UTC
I'm not really sure what to make of this one.  I really don't know if it's Coursier downloading the wrong thing, or our Nexus serving the wrong thing, or some combination of the two, but it's weird.

I have an artifact which is defined by a version range.  Specifically: `verizon.inf.delorean:core_2.11:1.1.+`.  There are several versions in this range available, but it isn't a very actively published project, so nothing new has been pushed in several weeks.  I also have several other artifacts which are non-deterministically exhibiting this problem.  I just picked this one.  Anyway, here's the error I get:

```
[error] (core/*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   verizon.inf.delorean:core_2.11:1.1.+:
[error]     not found:
[error]       ~/.ivy2/local/verizon.inf.delorean/core_2.11
[error]       https://repo1.maven.org/maven2/verizon/inf/delorean/core_2.11/maven-metadata.xml
[error]       https://oss.sonatype.org/content/repositories/releases/verizon/inf/delorean/core_2.11/maven-metadata.xml
[error]       http://nexus.oncue.verizon.net/nexus/content/groups/internal-ivy/verizon.inf.delorean/core_2.11/
[error]     wrong checksum: ~/.coursier/cache/v1/http/nexus.oncue.verizon.net/nexus/content/groups/internal/verizon/inf/delorean/core_2.11/maven-metadata.xml
```

If I wipe the `~/.coursier` directory and try again, generally it works.  Or at least, a different artifact(s) may fail.  I can also just delete this specific artifact and it will generally work.

What's happening is the `maven-metadata.xml.sha1` file contains the wrong hash.  As far as I can tell, it doesn't contain the right hash for _any_ of the xml files downloaded by Coursier, nor does it match the hash of any of the xml files in my entire Ivy2 cache.  It's basically just… wrong.  The `maven-metadata.xml` file looks right, and matches the contents of the `maven-metadata.xml` file from the appropriate artifact path in our Nexus.  Additionally, if I curl the `maven-metadata.xml.sha1` file which is also in the right place in our Nexus, I get a file which contains the right hash.

So it's sort of like Coursier just made up a hash that was wrong, stuck it in a file, and complains about it not matching.  :-)  Once this situation arises by the way (which is far more often than not with artifacts resolved from this Nexus), it never seems to fix itself.  Coursier is just permanently stuck with this artifact never matching its hash.

Again, I don't know if this is the fault of our Nexus in some way, or if Coursier legitimately has a bug, but it's pretty annoying.  :-)

**Comment by alexarchambault** [comment] 2016-08-23 23:21
I ran into vaguely similar issues at some point during the development of coursier, originating from non-thread safety in `java.net.HttpUrlConnection` it seemed. That would result in some downloaded files being empty or corrupted. Ensuring a given URL isn't downloaded twice in parallel fixed it, but you might be running into a more intricate similar bug...

I was recommended [okhttp](https://github.com/square/okhttp) as a safer alternative to `java.net.HttpUrlConnection`. 1.0.0-M14 (which should be released in a few hours) will also ship with an optional okhttp plugin, that can be enabled by adding
```scala
libraryDependencies += "io.get-coursier" %% "coursier-okhttp" % "1.0.0-M14"
```
along the `addSbtPlugin` adding sbt-coursier.

If we're really lucky here, it will solve that issue too...

**Comment by djspiewak** [comment] 2016-08-29 23:41
@alexarchambault Looks good so far, though a lot of these sorts of warnings:

```
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body?
Aug 29, 2016 5:40:44 PM com.squareup.okhttp.ConnectionPool pruneAndGetAllocationCountent-2.6.2.pom
```

**Comment by xsy233** [comment] 2016-09-01 04:47
@alexarchambault I ran into this today, will okhttp be the default http client?

**Comment by djspiewak** [comment] 2016-09-01 17:44
@alexarchambault Still seeing the checksum error, even with okhttp.  Certainly not as frequent, but it's happening.

**Comment by djspiewak** [comment] 2016-09-09 17:33
I've still *only* seen this in artifacts resolved from this specific Nexus.  Another private Nexus (yes… uh, we have more than one… don't ask) has no such issues that I've seen.  So that strongly implies that there's something weird about our setup, but I'm not even sure where to start looking.

@alexarchambault Any suggestions as to what I should be looking for?

**Comment by djspiewak** [comment] 2016-09-16 06:33
Correction to the previous: I've now seen it with both Nexuses.  I think it may be related to bandwidth.  It's far easier to reproduce on a low bandwidth, high latency connection than it is on the inverse.

**Comment by djspiewak** [comment] 2016-10-10 16:48
I forgot to update here, but shortly after my previous comment, I actually saw this issue with an artifact resolved from Maven Central.  That appears to be extremely rare, but it *has* happened, so we can rule out the "private nexus" qualifier.

**Comment by djspiewak** [comment] 2016-10-10 17:35
Sorry to spam this issue…  I've *finally* managed to see the issue without coursier.  I can actually reproduce (at least with our Nexus) the http server itself serving up an incorrect `.sha1` file via `curl`.  It's not deterministic, but I can reproduce it.  Coursier is getting that incorrect file (only when it hits the problem, obviously), and in turn fails the build.  Given that Nexus is actually serving up wrong files, it looks like Ivy is just straight-up ignoring checksum errors (or retrying until it's not errored maybe?).

As a sidebar, `coursierChecksums in ThisBuild := Nil` doesn't change anything.

**Comment by eryshev** [comment] 2016-11-08 13:21
I have the same problem.
Is there some workaround to deal with it?

**Comment by djspiewak** [comment] 2016-11-08 17:29
Oh I forgot to update the issue…

So I found the root cause of this, and also a workaround.  First, the workaround:

```sbt
coursierChecksums := Nil
```

Put that in every `build.sbt` file, or add it to the default settings of every project. Using `in ThisBuild` doesn't work for some reason, but that setting *does* work.  Now, for the root cause…

Any Nexus instance which is load-balanced is going to have some metadata syncing between the instances when artifacts are published.  This sync has a (sometimes significant!) lag, due to the way that Nexus is designed.  So one instance will have a revised artifact-level metadata XML file, while the other will still have the old file.  Coursier necessarily makes two separate connections to acquire the metadata XML and its checksum.  If these two connections are load balanced to separate instances while the instances are out of sync, Coursier will acquire either stale metadata or a stale checksum.  It may actually acquire *both* in a stale state, but that doesn't lead to errors.

Of course, Ivy isn't immune to this either, so I think one of two things are happening.  Either Ivy is more forgiving of checksum failure on the artifact-level metadata, or it simply attempts to re-fetch the metadata or its checksum (or both) a few times in the event of a checksum failure.  With Coursier, the metadata for that artifact is effectively permanently corrupted (well, until the refresh timeout), since from Coursier's perspective, the metadata has already been fetched!

@alexarchambault I think one solution that could be explored here is simply immediately expiring the metadata for any artifacts where the checksum doesn't match.  That would still result in a build failure, but at least users could retry.  A slightly more sophisticated solution would involve some retries.

**Comment by dwijnand** [comment] 2016-11-08 17:33
As a side note in ThisBuild doesn't work for coursier because coursier sets everything in project scope, which removes all chance of using anything but project scope to change the behaviour.

**Comment by eryshev** [comment] 2016-11-08 21:26
@djspiewak thx for your explanation but I only have one Nexus instance so I don't think it's the root cause for me.
Anyway I'll try `coursierChecksums := Nil` workaround tomorrow.
I am really look forward to use Coursier for my project because it speeds up my dependency resolving step in nearly 8 times :)

**Comment by eryshev** [comment] 2016-11-09 16:52
So i've finished with:
`
import coursier.CoursierPlugin.autoImport._

coursierChecksums := Nil
coursierArtifactsChecksums := Nil
`
in my ~/.sbt/0.13/coursier.sbt and it works.

**Comment by hepin1989** [comment] 2017-08-31 05:20
![image](https://user-images.githubusercontent.com/501740/29907645-24a9a48a-8e4f-11e7-9992-a43106cbb055.png)

I got this issue too,so go a Nil.

**Comment by schmitch** [comment] 2018-06-26 13:30
I get the following error:

```
Downloading https://URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
Downloaded https://URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml.sha1
Downloading https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
Downloading https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml.sha1
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] (eip / coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] (messaging / coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] (eip / ssExtractDependencies) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:

[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] (messaging / ssExtractDependencies) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     io.netty:netty-codec-http2:[4.1.22.Final]:
[error]         No version found for [4.1.22.Final]
[error]         not found:
[error]             /Users/schmitch/.ivy2/local/io.netty/netty-codec-http2
[error]             https://URI/repository/internal-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/internal/io/netty/netty-codec-http2/maven-metadata.xml
[error]             https://URI/repository/public/io/netty/netty-codec-http2/maven-metadata.xml
[error]         wrong checksum: /Users/schmitch/Library/Caches/Coursier/v1/https/schmitch%40URI/repository/mvn-releases/io/netty/netty-codec-http2/maven-metadata.xml
[error] Total time: 3 s, completed 26.06.2018 15:26:38
[info] shutting down server
```

basically what's strange is that only mvn-releases will have the netty-codec-http2 while all the others won't have netty-codec-http2 so maven-metadata.xml is of course empty

**Comment by skisel** [comment] 2018-08-04 08:43
same issue here, also with netty-codec-http2:4.1.22.Final
What's so special about netty-codec-http2?

**Comment by alexarchambault** [comment] 2019-06-21 14:41
Closing this. Checksum errors should now result in the underlying file and its checksum files being deleted from the cache, and attempted to be downloaded again, which should solve that issue (since `1.1.0-M14-5` and https://github.com/coursier/coursier/commit/4e4501360f8e1e4a58381758a54f21c1e3185476 for the checksum file, and way before that for the underlying file).

**Closed by alexarchambault** 2019-06-21 14:41 UTC
Labels: bug
