### ISSUE TITLE
`sbt new` doesn't work

### ISSUE THREAD

**Issue by lrytz** [coursier/coursier#1696] opened 2020-05-01 11:36 UTC
```
luc@luclin:~/sandbox$ sbt new scala/scala-seed.g8
Exception in thread "main" java.lang.Exception: Don't know what Scala version should be used for sbt version ''
	at coursier.sbtlauncher.SbtConfig.fillMissing(SbtConfig.scala:53)
```

Related to https://github.com/scala/scala-lang/pull/1130#discussion_r410988941

**Comment by sloshy** [comment] 2020-05-20 02:18
Seems this is a duplicate of https://github.com/coursier/sbt-launcher/issues/151. There is a workaround where if you specify the sbt version as a java property with `-D` then it works (described in the linked issue).

Maybe also another thing to consider RE: https://github.com/coursier/coursier/issues/1714 (if this coursier-specific sbt launcher will stay the default)

**Comment by julienrf** [comment] 2022-02-08 08:15
I think we can close this issue:

~~~ text
$ which sbt
/home/julien/.local/share/coursier/bin/sbt
$ sbt new scala/scala3.g8
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 11.0.6)
[info] loading settings for project global-plugins from idea.sbt ...
[info] loading global plugins from /home/julien/.sbt/1.0/plugins
[info] set current project to new (in build file:/tmp/sbt_d4d32abb/new/)

A template to demonstrate a minimal Scala 3 application 

name [Scala 3 Project Template]: it works

Template applied in /tmp/./it-works
~~~

**Closed** 2022-02-08 09:21 UTC
