### ISSUE TITLE
SBT+coursier running out of memory on spark build [1.02, 1.1.0-M1]

### ISSUE THREAD

**Issue by dansanduleac** [coursier/coursier#816] opened 2018-03-17 00:52 UTC
See example builds:
* 3G - https://circleci.com/gh/palantir/spark/2131
* 4G
   - https://circleci.com/gh/palantir/spark/2134 (this one just timed out with no output after 10m, suspecting similar issue w/ memory pressure)
   - https://circleci.com/gh/palantir/spark/2136 (this time it did throw `OutOfMemoryError`)

Successful build before attempting to move to coursier:
https://circleci.com/gh/palantir/spark/2113
Only other changes we made on top of that build were small, namely:
* manually set up each Project's `dependencyManagement` from the resolved effective pom (that comes from sbt-pom-reader), in order to get transitive exclusions
* manually add `libraryExclusions` to account for a behaviour difference - the dependencyManagement exclusions only seem to apply to _direct_ dependencies of a module which defines exclusions, whereas the maven build applies the exclusions to the whole subtree introduced by that module

Build runs fine with -Xmx2g without coursier, but throws a GC Overhead Limit Exceeded error if I use coursier (tried either version mentioned in the title).

Aside from bumping the memory, I attempted to set up class unloading as well as turning on CMS GC - https://github.com/palantir/spark/pull/326/files#diff-876e7879bb7916916afca05ef15596a4R135
But that didn't seem to help.

**Comment by alexarchambault** [comment] 2018-03-18 21:50
Simply adding sbt-coursier `1.0.2` to the sources of spark `2.2.1` (in `project/plugins.sbt` and `project/project/plugins.sbt`), and running
```
$ sbt -J-Xmx2g update compile test:compile
```
on clean sources worked fine for me (on OS X though).

So I'm not sure what can cause the OOM or GC overhead in your case… Are you using the same version of sbt-coursier? (I can think of some changes late during the RC cycle that may have saved some memory…)

**Comment by dansanduleac** [comment] 2018-05-01 13:25
That's quite right @alexarchambault. I figured out what was happening in my case.
Turns out, if I had already done a resolution using ivy, and then I enable coursier, I get an OOM pretty much every time.
The exact same happens on a clean build that starts using coursier, but then I remove the coursier plugin.

**Comment by alexarchambault** [comment] 2019-05-07 09:09
Closing for now. Not sure what the problem is, seems it's not specific to coursier…

**Closed by alexarchambault** 2019-05-07 09:09 UTC
Labels: details needed, sbt-coursier
