### ISSUE TITLE
Coursier does not run on Apple M1 Silicon

### ISSUE THREAD

**Issue by ironfish** [coursier/coursier#2335] opened 2022-01-21 19:21 UTC
Failed to execute process '/opt/homebrew/bin/cs'. Reason:
exec: Bad CPU type in executable

**Comment by bishabosha** [comment] 2022-01-27 11:02
cs won't work until graalvm supports apple silicon

**Comment by keynmol** [comment] 2022-01-27 11:07
Which prompted me to look at the current status: https://github.com/oracle/graal/issues/2666#issuecomment-1010183689

Which is all good news, and especially with them hooking up M1 to the infra, to produce images for 17 (and after that backport for 11)

In the meantime I recommend using a jar-based launcher: https://get-coursier.io/docs/cli-installation#linux-macos-1

This means that the JDK must be managed externally (i.e. install a M1-compatible adoptium/zulu/liberica), and then the launcher jar will run correctly (and correctly detect the architecture, which won't happen if you force to run coursier native through Rosetta)

**Comment by jorhett** [comment] 2022-02-03 23:11
Seems to be working as of today?

```shell
$ uname -a
Darwin mymbp 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

$ brew install coursier/formulas/coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M4/coursier
...snip...

$ cs setup --yes
Checking if a JVM is installed
https://github.com/coursier/jvm-index/raw/master/index.json
  100.0% [##########] 639.0 KiB (282.6 KiB / s)
No JVM found, should we try to install one? [Y/n] Y
Should we update ~/.profile, ~/.bash_profile? [Y/n] Y
Some shell configuration files were updated. It is recommended to close this terminal once the setup command is done, and open a new one for the changes to be taken into account.

Checking if ~/Library/Application Support/Coursier/bin is in PATH
Should we add ~/Library/Application Support/Coursier/bin to your PATH via ~/.profile, ~/.bash_profile? [Y/n] Y

Checking if the standard Scala applications are installed
  Installed ammonite
  Installed cs
  Installed coursier
  Installed scala
  Installed scalac
  Installed sbt
  Installed sbtn
  Installed scalafmt
```

**Comment by mtomko** [comment] 2022-02-03 23:26
I can't reproduce it:
```shell
 uname -a
Darwin mbp14.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
 ~  brew install coursier/formulas/coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M4
Already downloaded: /Users/mark/Library/Caches/Homebrew/downloads/81f6e90f03462d1223e426f9a3387f85a73483d57b744aa68778a6f85b48569e--coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M4
Already downloaded: /Users/mark/Library/Caches/Homebrew/downloads/4dec6448811f472e88800e802090b8811ef89196f81f4884be2b53bb3c993dbd--cs-x86_64-apple-darwin.gz
==> Installing coursier from coursier/formulas
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/coursier/2.1.0-M4: 5 files, 57.3MB, built in 2 seconds
==> Running `brew cleanup coursier`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 ~  cs
zsh: bad CPU type in executable: cs
 ✘  ~  coursier setup --yes
Checking if a JVM is installed
Found a JVM installed under /Users/mark/.sdkman/candidates/java/current.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
JVM graalvm:19.3 not found in index: JVM graalvm not found
```

**Comment by jorhett** [comment] 2022-02-03 23:35
@mtomko private tip from my experience --  make sure you don't have a different `cs` bin in your path. In particular, homebrew puts the binary in `/opt/homebrew/bin/` on non-Intel platforms, so if you have cs in `/usr/local/bin` or `~/Library/Application Support/Coursier/bin` it will keep using it

If you migrated your macbook from an Intel and kept the programs in /usr/local you're going to have many problems with this.

Brew works even with old intel packages, so `/usr/local/bin/brew uninstall coursier` will likely work.

The following will probably get most of the leftovers
  `rm -rf ~/Library/Application Support/Coursier ~/Library/Caches/Coursier /usr/local/bin/cs`

**Comment by mtomko** [comment] 2022-02-04 00:08
I thought of that. `cs` is only on my path when I install coursier via homebrew, and it goes away when I uninstall it:
```shell
brew install coursier/formulas/coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M4
Already downloaded: /Users/mark/Library/Caches/Homebrew/downloads/81f6e90f03462d1223e426f9a3387f85a73483d57b744aa68778a6f85b48569e--coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M4
Already downloaded: /Users/mark/Library/Caches/Homebrew/downloads/4dec6448811f472e88800e802090b8811ef89196f81f4884be2b53bb3c993dbd--cs-x86_64-apple-darwin.gz
==> Installing coursier from coursier/formulas
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/coursier/2.1.0-M4: 5 files, 57.3MB, built in 2 seconds
==> Running `brew cleanup coursier`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 ~  which coursier
/opt/homebrew/bin/coursier
 ~  which cs
/opt/homebrew/bin/cs
 ~  ls -l /opt/homebrew/bin/cs
lrwxr-xr-x  1 mark  admin  34 Feb  3 16:07 /opt/homebrew/bin/cs -> ../Cellar/coursier/2.1.0-M4/bin/cs

**Comment by mtomko** [comment] 2022-02-04 00:12
Also, the 2.1.0-M4 release artifacts don't include an M1 executable:
https://github.com/coursier/coursier/releases/tag/v2.1.0-M4
And the homebrew formulas default to X86:
https://github.com/coursier/homebrew-formulas/blob/master/coursier.rb

**Comment by ironfish** [comment] 2022-02-04 17:10
Yeah, no joy. Isn't going to work until an M1 version of GraalVM is released.

**Comment by keynmol** [comment] 2022-02-04 17:49
And even after that it might be problematic until GHA add a M1 runner - otherwise there's no way to produce M1 native binaries on CI.

**Comment by bishabosha** [comment] 2022-02-04 19:00
I find `coursier` (jar based launcher) fast enough to not need the native binary, however `coursier setup` is still broke by no graalvm of course, so I just manually run `coursier install scala` etc.

**Comment by alexarchambault** [comment] 2022-02-06 19:48
> And even after that it might be problematic until GHA add a M1 runner - otherwise there's no way to produce M1 native binaries on CI.

I don't know how it will actually be supported by GraalVM, but sometimes, generating ARM64-compatible binaries works on x86_64, and is just a matter of passing `-arch arm64` to the right C compiler or linker invocations. So we _might_ be fine.

**Comment by alexarchambault** [comment] 2022-02-06 19:50
> however coursier setup is still broke by the lack of graalvm of course, so I just manually run coursier install scala etc.

@bishabosha This needs to be fixed IMO. I know the architecture isn't checked carefully enough in some parts of coursier… Do you know the exact step that fails during `cs setup`?

**Comment by bishabosha** [comment] 2022-02-07 10:51
> @bishabosha This needs to be fixed IMO. I know the architecture isn't checked carefully enough in some parts of coursier… Do you know the exact step that fails during `cs setup`?

it seems to be after installing `ammonite` then the CLI shows scanning jars, then there is the error `JVM graalvm:19.3 not found in index: JVM graalvm not found` - described in https://github.com/coursier/coursier/issues/2065.

**Comment by marcraminv** [comment] 2022-02-23 14:47
Hey,
I was able to make `./cs setup` (not sure if happens because I installed Rosetta) my point is... Even having `cs` not compatible with M1, could we make explicit in some way to install a `arm64` jdk like `zulu:11.0.14` when is doing `./cs java --jvm zulu:11.0.14 --setup` ? 

I have checked the jvm index list and the arm version is there, but cs is not able to get the correct os type

**Comment by zhenglaizhang** [comment] 2022-04-09 11:01
How can I install the arm64 JDK. 
For my working repos I will use x64 JDk for compatabily reasons, while for my personal project I would. prefer arm64 JDk for perf reasons. But I cannot find any way to pass the arch related flags to `cs`

**Comment by bishabosha** [comment] 2022-04-10 02:39
> How can I install the arm64 JDK.
> For my working repos I will use x64 JDk for compatabily reasons, while for my personal project I would. prefer arm64 JDk for perf reasons. But I cannot find any way to pass the arch related flags to `cs`

I use homebrew's openjdk which is built for apple silicon

**Comment by kevinsjoberg** [comment] 2022-04-27 10:44
It looks like GraalVM now officially supports Apple Silicon (M1). See [this](https://github.com/oracle/graal/issues/2666). What is now needed to get official support in Coursier?

**Comment by alexarchambault** [comment] 2022-08-18 17:50
FYI there are now M1 coursier launchers in the GitHub release assets of [VirtusLab/coursier-m1](https://github.com/VirtusLab/coursier-m1).

**Comment by MrPowers** [comment] 2022-08-19 13:32
@alexarchambault - thank you!  Can you please send the commands to download a version of Java that's suitable for a Mac M1 (preferably Java 11).  I can see the Java versions with `cs java --available`, but not sure which one I should download.  Thank you!

**Comment by bishabosha** [comment] 2022-08-19 13:43
you can use the temurin:18,  graalvm-java17:22.2.0 I use both on my m1 macbook pro 14

**Comment by julienrf** [comment] 2023-01-17 12:28
Related PR: https://github.com/VirtusLab/coursier-m1/pull/28

**Comment by julienrf** [comment] 2023-03-10 12:49
I am closing this issue since `cs` does run on Apple Silicon machines. https://github.com/coursier/coursier/issues/2537 tracks the issue with `cs setup` not working on those machines.

**Closed by julienrf** 2023-03-10 12:49 UTC
Labels: UX, high priority

**Comment by SethTisue** [comment] 2023-06-13 02:04
I'm not currently able to reproduce this on my Mac 🎉

**Comment by ironfish** [comment] 2023-06-13 18:40
Seems to be working for me as well.
