### ISSUE TITLE
cs setup keeps failing

### ISSUE THREAD

**Issue by jcakstins** [coursier/coursier#2201] opened 2021-09-30 21:00 UTC
Installed coursier on my Mac (MacOS Big Sur 11.5.2 ) using homebrew. Unable to run the initial setup as I get the following error.

```
cs setup
Checking if a JVM is installed
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/shyiko/jabba/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://github.com/shyiko/jabba/raw/master/index.json
	at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:141)
	at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:139)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

coursier version installed 2.0.13

**Comment by jorhett** [comment] 2022-02-03 23:17
Try using `brew install coursier/formulas/coursier`

**Comment by julienrf** [comment] 2023-07-03 14:46
I am closing this issue since I am unable to reproduce it. Feel free to comment if we need to re-open it.

**Closed by julienrf** 2023-07-03 14:46 UTC
