### ISSUE TITLE
Remove Scalaz dependency

### ISSUE THREAD

**Issue by leonardehrenfried** [coursier/coursier#757] opened 2018-01-28 14:49 UTC
@alexarchambault has been publicly on board with removing scalaz as a dependency: https://github.com/sbt/librarymanagement/pull/190#issuecomment-352363689

This is a prerequisite for sbt starting to ship with coursier support itself (not a plugin).

From a cursory look at the code it seems that the main usages are `Task`, `\/`, `EitherT`. It's not an impossible task to replace these.

The question is: What should it be replaced with?

From my point of view there are a few options:

1. Copy the parts of Scalaz that are actually used.
2. Rewrite the parts that are actually used with types that enhance stdlib functionality.
3. Use another functional library, for example cats.

In my view 3. does not improve the dependency situation much.

So 1. and 2. are more promising.

I'm not sure however, how easy it is to take a part of scalaz and copy it without having to bring in a huge chunk of the rest of the library.

On the other hand, writing a replacement might also be a never-ending project, as the devil is probably in the details.

One approach could be to go type by type, ie. set the goal to remove a single type first and learn from the experiences of doing that. For example, we could introduce a `coursier.concurrent.Task` and see how far we get.

WDYT?

**Comment by wisechengyi** [comment] 2018-02-01 22:12
Can we rely on upgrading to 2.12 to leverage `Either` being a built in, or is that infeasible because `Either` is now used in core so it has to be backwards compatible with 2.10 and 2.11?

**Comment by eed3si9n** [comment] 2018-02-02 00:26
Duplicate of https://github.com/coursier/coursier/issues/175

**Comment by alexarchambault** [comment] 2018-02-04 23:41
> Duplicate of https://github.com/coursier/coursier/issues/175
Yep, closing to keep the discussion in https://github.com/coursier/coursier/issues/175.

**Closed by alexarchambault** 2018-02-04 23:41 UTC
