### ISSUE TITLE
coursier Linux launcher broken

### ISSUE THREAD

**Issue by randov** [coursier/coursier#2624] opened 2022-12-14 15:35 UTC
```
bash-4.2# curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20.1M  100 20.1M    0     0  9511k      0  0:00:02  0:00:02 --:--:-- 37.0M
bash-4.2# chmod +x ./cs
bash-4.2# ./cs setup
./cs: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./cs)
./cs: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./cs)
```

The linux used:
```
bash-4.2# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Previous version of the launcher was working on the same Linux container.

**Comment by tgodzik** [comment] 2022-12-14 16:05
Thanks for reporting! That looks like an issue with updated ubuntu image. We run the release on the latest. It's possible that if you update your system the error will go away.

In the meantime I'll update the jobs.

**Comment by alexarchambault** [comment] 2022-12-14 16:09
It seems we should do just like how Scala CLI does: it generates its Linux binaries from a docker container. mill-native-image should allow to do that easily.

**Comment by tgodzik** [comment] 2022-12-14 16:30
> It seems we should do just like how Scala CLI does: it generates its Linux binaries from a docker container. mill-native-image should allow to do that easily.

Those are already images, we can just pin it for now. Change like https://github.com/coursier/coursier/pull/2625 worked for bloop

**Comment by andriygm** [comment] 2022-12-21 17:24
Issue still seems to be present on my Debian 11 machine. Using v2.1.0-RC2 seems to work for now.

**Comment by miamagana** [comment] 2023-01-16 16:26
Issue still present when trying to build it using Ubuntu 20.04

**Comment by lwronski** [comment] 2023-01-21 16:20
> I confirm that the issue is still present in 2.1.0-RC4 (with Ubuntu on an x86_64 arch)

Can you try to install `static` launcher of `cs`? I suppose it should work. The cs `static` launcher can be found in the release [assets](https://github.com/coursier/coursier/releases/tag/v2.1.0-RC5).

**Comment by julienrf** [comment] 2023-01-21 16:25
The static launcher works for me. But I think we understood the cause of the issue: we still build le native launchers from the Github runners instead of using a controlled OS.

**Comment by julienrf** [comment] 2023-01-23 15:08
I have tried the binary produced by this workflow: https://github.com/coursier/coursier/actions/runs/3987388680 and it worked for me!

Can we have other people confirm that that launcher works for them too?

Scroll down and download the “launchers” archive in the Artifacts section:

![image](https://user-images.githubusercontent.com/332812/214074088-be2dedcc-4026-4b49-bb9c-e10b4556f846.png)

Then extract the linux one (`cs-x86_64-pc-linux`), make it executable, and run it (e.g. `./cs-x86_64-pc-linux --version`).

**Comment by julienrf** [comment] 2023-01-24 14:07
Hello @miamagana, thank you for trying! It seems you still use the launcher of the latest release (2.1.0-RC5), not the one from my PR. I’ve just re-uploaded it here for convenience (and because the one attached to the Action will be automatically removed by GitHub tomorrow): [cs-x86_64-pc-linux.gz](https://github.com/coursier/coursier/files/10490677/cs-x86_64-pc-linux.gz)

**Comment by miamagana** [comment] 2023-01-24 15:14
Hey @julienrf, thanks for the heads-up!

I am now getting a different error when installing Scala, the `cs setup` command works fine as expected. 

But when executing `cs install scala` command the following error is thrown.

```
#8 0.291 /root/.local/share/coursier/bin/.cs.aux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/.local/share/coursier/bin/.cs.aux)                                                               
#8 0.291 /root/.local/share/coursier/bin/.cs.aux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/.local/share/coursier/bin/.cs.aux)
```

It seems like the same error but on another place, right?

**Comment by julienrf** [comment] 2023-01-24 15:34
It will be fixed in the next release.

**Comment by miamagana** [comment] 2023-01-24 15:40
> It will be fixed in the next release.

Lovely! Your suggestion solves the issue.

**Closed** 2023-01-24 15:42 UTC
Labels: high priority
