### ISSUE TITLE
Coursier 1.0.0 fails under Windows Subsystem for Linux

### ISSUE THREAD

**Issue by mslinn** [coursier/coursier#716] opened 2017-12-16 04:44 UTC
[This little project using Coursier](https://github.com/mslinn/sbtTemplate/blob/master/project/plugins.sbt#L1-L3) works fine under Linux, but fails under Windows Subsystem for Linux with the message `java.lang.NoSuchMethodError: coursier.ivy.Pattern.<init>(Lscala/collection/Seq;)V`

Here is the full error:
```
$ sbt
[info] Loading global plugins from /home/mslinn/.sbt/0.13/plugins
[info] Loading project definition from /mnt/c/work/experiments/sbt/sbtTemplate/project
[info] Updating {file:/mnt/c/work/experiments/sbt/sbtTemplate/project/}sbttemplate-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]
[warn]  * net.databinder:unfiltered_2.10:0.8.4 is selected over 0.7.0
[warn]      +- net.databinder:unfiltered-filter_2.10:0.8.4        (depends on 0.8.4)
[warn]      +- net.databinder:unfiltered-directives_2.10:0.8.4    (depends on 0.8.4)
[warn]      +- net.databinder:unfiltered-netty_2.10:0.7.0         (depends on 0.7.0)
[warn]
[warn]  * net.databinder:unfiltered-util_2.10:0.8.4 is selected over 0.7.0
[warn]      +- net.databinder:unfiltered_2.10:0.8.4               (depends on 0.8.4)
[warn]      +- net.databinder:unfiltered-jetty_2.10:0.8.4         (depends on 0.8.4)
[warn]      +- net.databinder:unfiltered-netty-server_2.10:0.7.0  (depends on 0.7.0)
[warn]
[warn]  * io.netty:netty:3.9.2.Final is selected over 3.6.4.Final
[warn]      +- com.ning:async-http-client:1.8.10                  (depends on 3.9.2.Final)
[warn]      +- net.databinder:unfiltered-netty_2.10:0.7.0         (depends on 3.6.4.Final)
[warn]
[warn]  * org.scalaz:scalaz-concurrent_2.10:7.2.16 is selected over 7.1.2
[warn]      +- io.get-coursier:coursier-cache_2.10:1.0.0          (depends on 7.2.16)
[warn]      +- io.get-coursier:coursier-cache-java-6_2.10:1.0.0-M12-1 (depends on 7.1.2)
[warn]
[warn]  * org.scalaz:scalaz-effect_2.10:7.2.16 is selected over {7.1.2, 7.2.5}
[warn]      +- org.scalaz:scalaz-concurrent_2.10:7.2.16           (depends on 7.2.16)
[warn]      +- com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.10, sbtVersion=0.13) (depends on 7.2.5)
[warn]      +- org.scalaz:scalaz-concurrent_2.10:7.1.2            (depends on 7.1.2)
[warn]
[warn]  * org.scalaz:scalaz-core_2.10:7.2.16 is selected over {7.1.2, 7.2.5}
[warn]      +- org.scalaz:scalaz-effect_2.10:7.2.16               (depends on 7.2.16)
[warn]      +- io.get-coursier:coursier_2.10:1.0.0                (depends on 7.2.16)
[warn]      +- org.scalaz:scalaz-concurrent_2.10:7.2.16           (depends on 7.2.16)
[warn]      +- com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.10, sbtVersion=0.13) (depends on 7.2.5)
[warn]      +- io.get-coursier:coursier-java-6_2.10:1.0.0-M12-1   (depends on 7.1.2)
[warn]      +- org.scalaz:scalaz-concurrent_2.10:7.1.2            (depends on 7.1.2)
[warn]      +- org.scalaz:scalaz-effect_2.10:7.1.2                (depends on 7.1.2)
[warn]
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /mnt/c/work/experiments/sbt/sbtTemplate/project/target/scala-2.10/sbt-0.13/classes...
java.lang.NoSuchMethodError: coursier.ivy.Pattern.<init>(Lscala/collection/Seq;)V
        at coursier.ivy.PropertiesPattern$$anonfun$2.apply(Pattern.scala:48)
        at coursier.ivy.PropertiesPattern$$anonfun$2.apply(Pattern.scala:48)
        at scalaz.Validation.map(Validation.scala:113)
        at coursier.ivy.PropertiesPattern.substituteProperties(Pattern.scala:48)
        at coursier.ivy.PropertiesPattern$$anonfun$1.apply(Pattern.scala:26)
        at coursier.ivy.PropertiesPattern$$anonfun$1.apply(Pattern.scala:17)
        at scalaz.std.VectorInstances$$anon$1$$anonfun$traverseImpl$2$$anonfun$apply$2.apply(Vector.scala:36)
        at scalaz.ValidationInstances3$$anon$2.ap(Validation.scala:534)
        at scalaz.ValidationInstances3$$anon$2.ap(Validation.scala:526)
        at scalaz.Apply$class.ap2(Apply.scala:49)
        at scalaz.ValidationInstances3$$anon$2.ap2(Validation.scala:526)
        at scalaz.Applicative$class.apply2(Applicative.scala:32)
        at scalaz.ValidationInstances3$$anon$2.apply2(Validation.scala:526)
        at scalaz.std.VectorInstances$$anon$1$$anonfun$traverseImpl$2.apply(Vector.scala:36)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
        at scalaz.std.VectorInstances$$anon$1.traverseImpl(Vector.scala:35)
        at scalaz.std.VectorInstances$$anon$1.traverseImpl(Vector.scala:15)
        at scalaz.Traverse$Traversal.run(Traverse.scala:50)
        at scalaz.Traverse$class.traverse(Traverse.scala:62)
        at scalaz.std.VectorInstances$$anon$1.traverse(Vector.scala:15)
        at scalaz.Applicative$class.traverse(Applicative.scala:37)
        at scalaz.ValidationInstances3$$anon$2.traverse(Validation.scala:526)
        at scalaz.Traverse$class.traverseM(Traverse.scala:70)
        at scalaz.std.VectorInstances$$anon$1.traverseM(Vector.scala:15)
        at scalaz.syntax.TraverseOps.traverseM(TraverseSyntax.scala:22)
        at coursier.ivy.PropertiesPattern.substituteProperties(Pattern.scala:17)
        at coursier.ivy.PropertiesPattern$$anonfun$1.apply(Pattern.scala:26)
        at coursier.ivy.PropertiesPattern$$anonfun$1.apply(Pattern.scala:17)
        at scalaz.std.VectorInstances$$anon$1$$anonfun$traverseImpl$2$$anonfun$apply$2.apply(Vector.scala:36)
        at scalaz.ValidationInstances3$$anon$2.ap(Validation.scala:534)
        at scalaz.ValidationInstances3$$anon$2.ap(Validation.scala:526)
        at scalaz.Apply$class.ap2(Apply.scala:49)
        at scalaz.ValidationInstances3$$anon$2.ap2(Validation.scala:526)
        at scalaz.Applicative$class.apply2(Applicative.scala:32)
        at scalaz.ValidationInstances3$$anon$2.apply2(Validation.scala:526)
        at scalaz.std.VectorInstances$$anon$1$$anonfun$traverseImpl$2.apply(Vector.scala:36)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
        at scalaz.std.VectorInstances$$anon$1.traverseImpl(Vector.scala:35)
        at scalaz.std.VectorInstances$$anon$1.traverseImpl(Vector.scala:15)
        at scalaz.Traverse$Traversal.run(Traverse.scala:50)
        at scalaz.Traverse$class.traverse(Traverse.scala:62)
        at scalaz.std.VectorInstances$$anon$1.traverse(Vector.scala:15)
        at scalaz.Applicative$class.traverse(Applicative.scala:37)
        at scalaz.ValidationInstances3$$anon$2.traverse(Validation.scala:526)
        at scalaz.Traverse$class.traverseM(Traverse.scala:70)
        at scalaz.std.VectorInstances$$anon$1.traverseM(Vector.scala:15)
        at scalaz.syntax.TraverseOps.traverseM(TraverseSyntax.scala:22)
        at coursier.ivy.PropertiesPattern.substituteProperties(Pattern.scala:17)
        at coursier.Tasks$$anonfun$exceptionPatternParser$1.apply(Tasks.scala:459)
        at coursier.Tasks$$anonfun$exceptionPatternParser$1.apply(Tasks.scala:451)
        at coursier.CoursierPlugin$.<init>(CoursierPlugin.scala:149)
        at coursier.CoursierPlugin$.<clinit>(CoursierPlugin.scala)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
        at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.foreach(Stream.scala:548)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
        at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
        at scala.collection.AbstractTraversable.to(Traversable.scala:105)
        at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
        at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
        at scala.collection.immutable.List.$plus$plus(List.scala:193)
        at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:39)
        at sbt.Load$.loadPlugins(Load.scala:900)
        at sbt.Load$.loadPluginDefinition(Load.scala:857)
        at sbt.Load$.buildPlugins(Load.scala:852)
        at sbt.Load$.plugins(Load.scala:840)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:464)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.defaultLoad(Load.scala:39)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:187)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:61)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: coursier.ivy.Pattern.<init>(Lscala/collection/Seq;)V
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by wisechengyi** [comment] 2017-12-16 05:41
not sure if related, can't fetch from maven right now.
```
$ curl  https://search.maven.org/remotecontent?filepath=io/get-coursier/sbt-coursier/1.0.0/sbt-coursier-1.0.0.pom
Not Found
```

**Comment by mslinn** [comment] 2017-12-16 05:42
@wisechengyi Probably unrelated

**Comment by wisechengyi** [comment] 2017-12-16 06:05
ok managed to get it from https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22coursier_2.10%22

so the jar should contain `coursier.ivy.Pattern`
```
$ jar -tf coursier_2.10-1.0.0.jar  | grep 'coursier/ivy/Pattern'
coursier/ivy/Pattern$$anonfun$coursier$ivy$Pattern$$helper$1$1.class
coursier/ivy/Pattern$$anonfun$substituteVariables$1.class
coursier/ivy/Pattern$Chunk.class
coursier/ivy/Pattern$Chunk$Opt.class
coursier/ivy/Pattern$Chunk$Opt$$anonfun$string$6.class
coursier/ivy/Pattern$Chunk$Opt$.class
coursier/ivy/Pattern.class
coursier/ivy/Pattern$Chunk$.class
coursier/ivy/Pattern$Chunk$Const$.class
coursier/ivy/Pattern$.class
coursier/ivy/Pattern$Chunk$Var$.class
coursier/ivy/Pattern$Chunk$Var.class
coursier/ivy/Pattern$$anonfun$string$2.class
coursier/ivy/Pattern$$anonfun$coursier$ivy$Pattern$$helper$1$2.class
coursier/ivy/Pattern$Chunk$Const.class
```

You should be able to find this jar under in the ivy cache (`~/.ivy2` for unix, not sure where it is for windows), could you check the sha1 is `5d8cf7bb1c092450710ae318e23aecabdaa7dd16`?

**Comment by mslinn** [comment] 2017-12-16 18:02
Yes, I did find the correct version of coursier:
```
$ jar -tf ~/.ivy2/cache/io.get-coursier/coursier_2.10/jars/coursier_2.10-1.0.0.jar  | grep 'coursier/ivy/Pattern'
coursier/ivy/Pattern$$anonfun$coursier$ivy$Pattern$$helper$1$1.class
coursier/ivy/Pattern$$anonfun$substituteVariables$1.class
coursier/ivy/Pattern$Chunk.class
coursier/ivy/Pattern$Chunk$Opt.class
coursier/ivy/Pattern$Chunk$Opt$$anonfun$string$6.class
coursier/ivy/Pattern$Chunk$Opt$.class
coursier/ivy/Pattern.class
coursier/ivy/Pattern$Chunk$.class
coursier/ivy/Pattern$Chunk$Const$.class
coursier/ivy/Pattern$.class
coursier/ivy/Pattern$Chunk$Var$.class
coursier/ivy/Pattern$Chunk$Var.class
coursier/ivy/Pattern$$anonfun$string$2.class
coursier/ivy/Pattern$$anonfun$coursier$ivy$Pattern$$helper$1$2.class
coursier/ivy/Pattern$Chunk$Const.class
```
I also found other, older versions of coursier, which did not have the method. After deleting the entire `~/.ivy2/cache/io.get-coursier` directory, I ran sbt and saw it fetch older versions of coursier:
```
[info] downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-java-6_2.10/1.0.0-M12-1/coursier-java-6_2.10-1.0.0-M12-1.jar ...
[info]  [SUCCESSFUL ] io.get-coursier#coursier-java-6_2.10;1.0.0-M12-1!coursier-java-6_2.10.jar (400ms)
[info] downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cache-java-6_2.10/1.0.0-M12-1/coursier-cache-java-6_2.10-1.0.0-M12-1.jar ...
[info]  [SUCCESSFUL ] io.get-coursier#coursier-cache-java-6_2.10;1.0.0-M12-1!coursier-cache-java-6_2.10.jar (244ms)
```
Then I thought that the version of sbt might be an issue:
```
$ cat project/build.properties
sbt.version=0.13.16
```
So after upgrading to sbt 1.0.4 I tried again, and it fetched the correct version of coursier:
```
[SUCCESSFUL ] io.get-coursier#sbt-shared;1.0.0!sbt-shared.jar (490ms)
```
Don't know why sbt 0.13.16 fetches the wrong/old version of coursier when running under Windows Subsystem for Linux. It is nice to know that sbt 1.0.4 does not have this problem. Perhaps another sbt plugin is somehow affecting this behavior, or perhaps the eviction warnings are significant, or perhaps it is an sbt 0.13.16 bug?

**Comment by wisechengyi** [comment] 2017-12-21 01:23
Closing this since the issue is resolved. Feel free to re-open if it pops again, which warrants a deeper look.

**Closed by wisechengyi** 2017-12-21 01:23 UTC
