### ISSUE TITLE
"checksum format error" occurs for binary checksum files

### ISSUE THREAD

**Issue by pfn** [coursier/coursier#356] opened 2016-10-04 19:11 UTC
I don't know where this is documented, but it turns out that binary checksum files are allowed (ivy and maven both support them). coursier chokes:

```
> compile
[info] Updating g2
Downloading https://repo1.maven.org/maven2/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom.sha1
Downloading https://repo1.maven.org/maven2/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom
[warn] Android SDK updates available, run 'android-update' to update:
[warn]     Android SDK Platform-Tools 24.0.3
[warn]     Google APIs Intel x86 Atom_64 System Image
[warn]     Google APIs Intel x86 Atom System Image
[warn] libraryDependencies have changed, forcing clean build
[trace] Stack trace suppressed: run last *:coursierResolution for the full output.
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   com.google.android.gms:play-services-base:9.6.1:
[error]     checksum format error: C:\Users\pfnguyen\android-sdk-windows\extras\google\m2repository\com\google\android\gms\play-services-base\9.6.1\play-services-base-9.6.1.pom.sha1
[error]     not found:
[error]       C:\Users\pfnguyen\.ivy2\local\com.google.android.gms\play-services-base\9.6.1\ivys\ivy.xml
[error]       https://repo1.maven.org/maven2/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom
[error]       C:\Users\pfnguyen\android-sdk-windows\extras\android\m2repository\com\google\android\gms\play-services-base\9.6.1\play-services-base-9.6.1.pom
[error] Total time: 3 s, completed Oct 4, 2016 12:06:32 PM
```

repro steps:

```
$ mkdir binchecksums
$ cd binchecksums
$ mkdir project
$ echo 'addSbtPlugin("org.scala-android" % "sbt-android" % "1.6.18")' > project/plugins.sbt
$ echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14-3")' >> project/plugins.sbt
$ sbt "gen-android com.foo Foo"
$ echo 'libraryDependencies += "com.google.android.gms" % "play-services-base" % "9.6.1"' >> build.sbt
$ sbt update
```

**Comment by pfn** [comment] 2016-10-04 19:12
Also, the extraneous download lines are very misleading. Please squelch them.

```
Downloading https://repo1.maven.org/maven2/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom.sha1
Downloading https://repo1.maven.org/maven2/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom
```

These files are, in reality, pulled from local filesystem.

**Comment by kzys** [comment] 2017-01-12 04:51
What is the actual content of the sha1 file.

While I can't find the document about the binary checksum as you mentioned, what Ivy supports looks like what Coursier supports.
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.ivy/ivy/2.0.0-rc1/org/apache/ivy/util/ChecksumHelper.java#54

**Comment by kzys** [comment] 2017-01-14 15:47
I could reproduce the issue, but

```
% hexdump ~/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom.sha1
0000000 da 39 a3 ee 5e 6b 4b 0d 32 55 bf ef 95 60 18 90
0000010 af d8 07 09
0000014
% shasum ~/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom     
4f7fccb91c7bc510729e0142def1f24472614bf5  /Users/kazuyoshi/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom
%
```
The content of the sha1 file doesn't match the actual checksum. Hmm...

**Comment by kzys** [comment] 2017-01-14 16:14
The MD5 checksum is in binary form as well, but the value is at least correct.

```
% hexdump ~/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom.md5
0000000 67 29 bd 4b c4 5e 7f 8f d5 64 4f a5 79 11 ed 63
0000010
~/binchecksums @ aug12.local
% md5 < ~/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-base/9.6.1/play-services-base-9.6.1.pom
6729bd4bc45e7f8fd5644fa57911ed63
%
```

So Courier can try MD5 when SHA1 doesn't match, but I'm not sure that automatically downgrading to the weaker hashing algorithm is a good idea. Probably not from security perspective.

**Comment by pfn** [comment] 2017-01-19 17:32
Yeah, I don't know why the sha1 is incorrect  :-( -- Not sure what the correct solution to this problem will be at the moment.

**Comment by pfn** [comment] 2017-01-31 17:19
for reference https://code.google.com/p/android/issues/detail?id=232567

**Comment by dwijnand** [comment] 2017-03-08 14:18
Is `coursierChecksums := Nil` a workaround?

**Comment by emanresusername** [comment] 2018-02-05 21:15
i get `checksum format error` with `com.twitter.common#metrics;0.0.29` as well
[possibly related](https://github.com/twitter/commons/issues/348)

**Comment by alexarchambault** [comment] 2019-05-13 08:04
Closing, binary checksums should be supported for time already.

**Closed by alexarchambault** 2019-05-13 08:04 UTC
Labels: bug, enhancement
