### ISSUE TITLE
Renjin dependencies not resolved

### ISSUE THREAD

**Issue by pedromss** [coursier/coursier#407] opened 2016-12-06 15:37 UTC
For some reason while using `"org.renjin" % "renjin-script-engine" % "0.8.1886"` coursier resolves all dependencies, meaning that no error is thrown but a package is missing from the classpath: `java.lang.NoClassDefFoundError: org/tukaani/xz/XZInputStream`

When using sbt's default artifact fetcher this problem doesn't  happen.

**Comment by alexarchambault** [comment] 2016-12-07 10:52
Would you have a small repro?

```
$ coursier fetch \
    -r https://nexus.bedatadriven.com/content/groups/public \
    org.renjin:renjin-script-engine:0.8.1886
```
says coursier brings `org.tukaani:xz:1.0` (which itself has `org.tukaani.xz.XZInputStream`) in the classpath.

**Comment by dpfeiffer** [comment] 2016-12-14 20:01
@alexarchambault I think I have the same problem with `"com.github.tomakehurst" % "wiremock" % "2.4.1"`. Without coursier I have `com.github.tomakehurst.wiremock.client.WireMock` on the classpath, with coursier (event if fetches the dependency successfully to ~/.coursier/cache/...) I cannot compile.

**Comment by alexarchambault** [comment] 2017-02-28 11:02
@dpfeiffer The current master pulls the jar of wiremock (which `1.0.0-M15` doesn't). The fix will be included in the upcoming `1.0.0-M15-2`.

**Comment by alexarchambault** [comment] 2017-02-28 11:04
@pedromss I still can't reproduce your issue (both `1.0.0-M15` and the current master pull the jar of `org.tukaani:xz:1.0`).

**Comment by pedromss** [comment] 2017-03-01 09:35
I can't reproduce it either. If it happens again or something similar happens I will try to present an example at the time.

Close this if you want.

**Closed** 2018-10-29 10:33 UTC
Labels: bug, details needed
